### PR TITLE
#35:  add init configuration for rultor

### PR DESCRIPTION
**Pull request by danilkuznetsov**
Connect to #35

### CODE REVIEW

**Comment by vkuchyn** [comment]
@danilkuznetsov thanks!

**Comment by danilkuznetsov** [comment]
expect rultor answer @rultor hello

**Comment by vkuchyn** [comment]
@rultor merge, pls

**Comment by vkuchyn** [comment]
@danilkuznetsov failed - see log

**Comment by danilkuznetsov** [comment]
@rultor merge

**Comment by danilkuznetsov** [comment]
@rultor merge

**Comment by danilkuznetsov** [comment]
@vkuchyn rultor looks for config in the master branch and not reading my config, so you need to put my rultor config in master branch

**Comment by vkuchyn** [comment]
@danilkuznetsov let me merge with github - will se how is it going

**Comment by vkuchyn** [comment]
@danilkuznetsov now it is in master. You can make some changes, create new PR and we'll try to merge with rultor

**Pull request merged**
