### PR TITLE
update readme add travis build status indicator

### PR DESCRIPTION
**Pull request by danilkuznetsov**
connect to #35

### CODE REVIEW

**Comment by danilkuznetsov** [comment]
@rultor merge pls

**Comment by vkuchyn** [comment]
@rultor merge, pls

**Comment by danilkuznetsov** [comment]
@rultor  merge pls

**Comment by vkuchyn** [comment]
@rultor merge

**Comment by danilkuznetsov** [comment]
@rultor another attempt to  merge, pls

**Comment by vkuchyn** [comment]
@rultor merge

**Comment by vkuchyn** [comment]
@rultor merge, pls

**Comment by vkuchyn** [comment]
@danilkuznetsov hm, rultor is already in admin group

**Comment by danilkuznetsov** [comment]
@vkuchyn verify this restrictions https://help.github.com/articles/about-branch-restrictions/

**Comment by vkuchyn** [comment]
@rultor merge again

**Comment by vkuchyn** [comment]
@danilkuznetsov cool!!!

**Comment by danilkuznetsov** [comment]
@vkuchyn  yeah !!!

**Pull request merged**
