### PR TITLE
tests for controller and repo

### PR DESCRIPTION
**Pull request by sLisnychyi**
@vkuchyn 
please check
Connected to #6

### CODE REVIEW

**Comment by vkuchyn** [comment]
@sLisnychyi here are 37 PMD violations. I suppose, first you should fix these issues before review

**Comment by sLisnychyi** [comment]
@vkuchyn 
i exclude test classes, so i don't have additional violations.
Do you see them on test classes?

**Comment by vkuchyn** [comment]
@sLisnychyi I'm not sure where. Just pulled your changes and run checker - got 37 violations. Please, for future - before PR check if build is ok. Build okey means all tests are fine and qulice metrics are also fine. Here is a list of violations
```
[ERROR] /src/main/java/juja/microservices/gamification/jersey/UserControllerImpl.java[72-78]: Avoid if (x != y) ..; else ..; (ConfusingTernary)
[ERROR] /src/main/java/juja/microservices/gamification/jersey/UserControllerImpl.java[93-98]: Avoid if (x != y) ..; else ..; (ConfusingTernary)
[ERROR] /src/main/java/juja/microservices/gamification/jersey/UserControllerImpl.java[59-59]: Found non-transient, non-static member. Please mark as transient or provide accessors. (BeanMembersShouldSerialize)
[ERROR] /src/main/java/juja/microservices/gamification/model/entity/User.java[66-67]: Document empty constructor (UncommentedEmptyConstructor)
[ERROR] /src/main/java/juja/microservices/gamification/model/entity/User.java[157-157]: StringBuffer (or StringBuilder).append is called consecutively without reusing the target variable. (ConsecutiveAppendsShouldReuse)
[ERROR] /src/main/java/juja/microservices/gamification/model/entity/User.java[158-158]: StringBuffer (or StringBuilder).append is called consecutively without reusing the target variable. (ConsecutiveAppendsShouldReuse)
[ERROR] /src/main/java/juja/microservices/gamification/model/entity/User.java[159-159]: StringBuffer (or StringBuilder).append is called consecutively without reusing the target variable. (ConsecutiveAppendsShouldReuse)
[ERROR] /src/main/java/juja/microservices/gamification/model/entity/User.java[156-156]: StringBuffer (or StringBuilder).append is called 2 consecutive times with literal Strings. Use a single append with a single combined String. (ConsecutiveLiteralAppends)
[ERROR] /src/main/java/juja/microservices/gamification/model/entity/User.java[157-157]: StringBuffer (or StringBuilder).append is called 2 consecutive times with literal Strings. Use a single append with a single combined String. (ConsecutiveLiteralAppends)
[ERROR] /src/main/java/juja/microservices/gamification/model/entity/User.java[158-158]: StringBuffer (or StringBuilder).append is called 2 consecutive times with literal Strings. Use a single append with a single combined String. (ConsecutiveLiteralAppends)
[ERROR] /src/main/java/juja/microservices/gamification/model/entity/User.java[159-159]: StringBuffer (or StringBuilder).append is called 2 consecutive times with literal Strings. Use a single append with a single combined String. (ConsecutiveLiteralAppends)
[ERROR] /src/main/java/juja/microservices/gamification/model/entity/User.java[156-156]: StringBuffer constructor is initialized with size 21, but has at least 33 characters appended. (InsufficientStringBufferDeclaration)
[ERROR] /src/main/java/juja/microservices/gamification/model/repository/UserRepositoryImpl.java[55-55]: Found non-transient, non-static member. Please mark as transient or provide accessors. (BeanMembersShouldSerialize)
[ERROR] /src/main/java/juja/microservices/gamification/service/ServiceImpl.java[53-53]: Found non-transient, non-static member. Please mark as transient or provide accessors. (BeanMembersShouldSerialize)
[ERROR] /src/test/java/juja/microservices/gamification/jersey/UserControllerImplTest.java[24-24]: Found non-transient, non-static member. Please mark as transient or provide accessors. (BeanMembersShouldSerialize)
[ERROR] /src/test/java/juja/microservices/gamification/jersey/UserControllerImplTest.java[27-27]: Found non-transient, non-static member. Please mark as transient or provide accessors. (BeanMembersShouldSerialize)
[ERROR] /src/test/java/juja/microservices/gamification/jersey/UserControllerImplTest.java[36-36]: Local variable 'uuid' could be declared final (LocalVariableCouldBeFinal)
[ERROR] /src/test/java/juja/microservices/gamification/jersey/UserControllerImplTest.java[39-39]: Local variable 'resp' could be declared final (LocalVariableCouldBeFinal)
[ERROR] /src/test/java/juja/microservices/gamification/jersey/UserControllerImplTest.java[40-41]: Local variable 'expected' could be declared final (LocalVariableCouldBeFinal)
[ERROR] /src/test/java/juja/microservices/gamification/jersey/UserControllerImplTest.java[49-49]: Local variable 'uuid' could be declared final (LocalVariableCouldBeFinal)
[ERROR] /src/test/java/juja/microservices/gamification/jersey/UserControllerImplTest.java[50-50]: Local variable 'user' could be declared final (LocalVariableCouldBeFinal)
[ERROR] /src/test/java/juja/microservices/gamification/jersey/UserControllerImplTest.java[54-54]: Local variable 'resp' could be declared final (LocalVariableCouldBeFinal)
[ERROR] /src/test/java/juja/microservices/gamification/jersey/UserControllerImplTest.java[55-55]: Local variable 'expected' could be declared final (LocalVariableCouldBeFinal)
[ERROR] /src/test/java/juja/microservices/gamification/jersey/UserControllerImplTest.java[63-63]: Local variable 'userToString' could be declared final (LocalVariableCouldBeFinal)
[ERROR] /src/test/java/juja/microservices/gamification/jersey/UserControllerImplTest.java[64-64]: Local variable 'name' could be declared final (LocalVariableCouldBeFinal)
[ERROR] /src/test/java/juja/microservices/gamification/jersey/UserControllerImplTest.java[72-72]: Local variable 'users' could be declared final (LocalVariableCouldBeFinal)
[ERROR] /src/test/java/juja/microservices/gamification/jersey/UserControllerImplTest.java[74-74]: Local variable 'result' could be declared final (LocalVariableCouldBeFinal)
[ERROR] /src/test/java/juja/microservices/gamification/model/repository/UserRepositoryImplTest.java[38-38]: Unnecessary use of fully qualified name 'Assert.assertEquals' due to existing static import 'org.junit.Assert.*' (UnnecessaryFullyQualifiedName)
[ERROR] /src/test/java/juja/microservices/gamification/model/repository/UserRepositoryImplTest.java[11-11]: Avoid unused imports such as 'org.springframework.data.mongodb.core.MongoAction' (UnusedImports)
[ERROR] /src/test/java/juja/microservices/gamification/model/repository/UserRepositoryImplTest.java[15-15]: Avoid unused imports such as 'org.testng.annotations.BeforeMethod' (UnusedImports)
[ERROR] /src/test/java/juja/microservices/gamification/model/repository/UserRepositoryImplTest.java[23-23]: Found non-transient, non-static member. Please mark as transient or provide accessors. (BeanMembersShouldSerialize)
[ERROR] /src/test/java/juja/microservices/gamification/model/repository/UserRepositoryImplTest.java[26-26]: Found non-transient, non-static member. Please mark as transient or provide accessors. (BeanMembersShouldSerialize)
[ERROR] /src/test/java/juja/microservices/gamification/model/repository/UserRepositoryImplTest.java[35-35]: Local variable 'name' could be declared final (LocalVariableCouldBeFinal)
[ERROR] /src/test/java/juja/microservices/gamification/model/repository/UserRepositoryImplTest.java[36-36]: Local variable 'user' could be declared final (LocalVariableCouldBeFinal)
[ERROR] /src/test/java/juja/microservices/gamification/model/repository/UserRepositoryImplTest.java[37-37]: Local variable 'result' could be declared final (LocalVariableCouldBeFinal)
[ERROR] /src/test/java/juja/microservices/gamification/model/repository/UserRepositoryImplTest.java[43-43]: Local variable 'uuid' could be declared final (LocalVariableCouldBeFinal)
[ERROR] /src/test/java/juja/microservices/gamification/model/repository/UserRepositoryImplTest.java[44-44]: Local variable 'query' could be declared final (LocalVariableCouldBeFinal)
```

**Comment by vkuchyn** [comment]
@sLisnychyi BTW, tests are also part of project and readability of them even more important than readability of code. So all the codestyle rules are also actual for test code. It is not good practice to exclude checks from them

**Comment by sLisnychyi** [comment]
@vkuchyn 
fixed also tests

**Comment by vkuchyn** [comment]
@sLisnychyi many thanks. I will review as soon as possible )

**Comment by vkuchyn** [comment]
@sLisnychyi fixed all violations and pushed to upstream repository. I will close this and make another one.

**Pull request closed without merging**
