### PR TITLE
fix rultor config

### PR DESCRIPTION
**Pull request by danilkuznetsov**

### CODE REVIEW

**Comment by danilkuznetsov** [comment]
@vkuchyn pls merge

**Comment by vkuchyn** [comment]
@danilkuznetsov add to PR description
"Connect #40 " 40 - issue number

**Comment by vkuchyn** [comment]
@rultor merge

**Comment by vkuchyn** [comment]
@danilkuznetsov you asked to merge with github tools?

**Comment by danilkuznetsov** [comment]
connect to #35

**Comment by danilkuznetsov** [comment]
@vkuchyn yes, pls merge with github tools, because rultor not reading my config from pull request

**Comment by vkuchyn** [comment]
@danilkuznetsov done. Please, note about PR description, otherwise we have ugly picture in waffle

**Comment by danilkuznetsov** [comment]
@vkuchyn I realized their mistakes, thanks

**Pull request merged**
