### PR TITLE
#14 #Done #Created new Point and Comment interface and objects

### PR DESCRIPTION
**Pull request by sLisnychyi**
Connect #14

### CODE REVIEW

**Comment by sLisnychyi** [comment]
@vkuchyn done pls check

**Comment by vkuchyn** [comment]
@sLisnychyi please, in PR description provide text "Connect #14" as in https://github.com/JuniorsJava/microservices/pull/33 for example. Or in https://github.com/JuniorsJava/microservices/pull/32

**Comment by vkuchyn** [comment]
@sLisnychyi waiting for merge in https://github.com/JuniorsJava/microservices/pull/32.
For future - start working from master, not from local branch. If required changes from some branch - give us know, we will force review or development.

**Comment by vkuchyn** [comment]
@rultor merge

**Pull request merged**
